#!/usr/bin/env python3
"""
Global Documentation Generator
Creates keywords.md, index.md, and comprehensive_book.md
"""

import os
import re
from pathlib import Path
from datetime import datetime
from collections import defaultdict

class GlobalDocGenerator:
    def __init__(self, docs_path: str, repo_path: str):
        self.docs_path = Path(docs_path)
        self.repo_path = Path(repo_path)

    def generate_keywords_md(self):
        """Generate global keywords.md file."""
        print("Generating global keywords.md...")

        all_keywords = defaultdict(list)

        # Collect all keywords from all _kw.md files
        for kw_file in self.docs_path.rglob('*_kw.md'):
            try:
                with open(kw_file, 'r', encoding='utf-8') as f:
                    content = f.read()

                # Extract keywords (headers level 3)
                keywords = re.findall(r'^### (\w+)', content, re.MULTILINE)

                rel_path = kw_file.relative_to(self.docs_path)
                for kw in keywords:
                    all_keywords[kw].append(str(rel_path))

            except Exception as e:
                print(f"  Error processing {kw_file}: {e}")

        # Build keywords.md
        keywords_md = f"""# Global Keyword Index

## Overview

This file contains all keywords extracted from the entire repository, organized alphabetically.

**Total unique keywords**: {len(all_keywords)}
**Generated**: {datetime.now().isoformat()}

---

"""

        # Sort keywords alphabetically
        sorted_keywords = sorted(all_keywords.keys())

        # Group by first letter
        current_letter = ''
        for kw in sorted_keywords:
            first_letter = kw[0].upper()
            if first_letter != current_letter:
                current_letter = first_letter
                keywords_md += f"\n## {current_letter}\n\n"

            keywords_md += f"### {kw}\n\n"
            # List sources (limit to 10)
            for source_file in all_keywords[kw][:10]:
                keywords_md += f"- [{source_file}](./{source_file})\n"
            if len(all_keywords[kw]) > 10:
                keywords_md += f"\n*... and {len(all_keywords[kw]) - 10} more occurrences*\n"
            keywords_md += "\n"

        keywords_md += f"""
---
*Total keywords: {len(all_keywords)}*
*Generated by World's Best Repo Book Generator*
"""

        # Write file
        keywords_file = self.docs_path / 'keywords.md'
        with open(keywords_file, 'w', encoding='utf-8') as f:
            f.write(keywords_md)

        print(f"  Created keywords.md with {len(all_keywords)} unique keywords")

    def generate_index_md(self):
        """Generate root index.md file."""
        print("Generating root index.md...")

        # Get all top-level folders
        top_folders = []
        try:
            for item in sorted(self.docs_path.iterdir()):
                if item.is_dir() and not item.name.startswith('.'):
                    top_folders.append(item.name)
        except:
            pass

        index_md = f"""# Strix Documentation

## Welcome

This is the comprehensive documentation for the **Strix** security testing framework.

All documentation was automatically generated by the World's Best Repo Book Generator.

**Repository**: rbarfinezhadfeli0/strix
**Generated**: {datetime.now().isoformat()}

---

## Quick Navigation

- [📚 Comprehensive Book](./comprehensive_book.md) - Complete repository documentation in book form
- [🔑 Global Keywords Index](./keywords.md) - All keywords from A to Z
- [✅ Verification Report](./verification_report.md) - Link validation and file status
- [📋 Manifest](./manifest.json) - Metadata and checksums

---

## Repository Structure

"""

        # Add top-level folders
        for folder in top_folders:
            index_md += f"- [{folder}/](./{folder}/index.md)\n"

        index_md += """

---

## Documentation Organization

Each folder contains:
- **index.md** - File and subdirectory listing
- **doc.md** - Narrative context and architectural overview
- **sub.md** - Aggregated keyword index

Each file has:
- **{filename}_docs.md** - Comprehensive documentation
- **{filename}_kw.md** - Extracted keywords

---

## About Strix

Strix is an AI-powered security testing framework that uses language models to perform
automated security assessments. It includes:

- **Agents**: Autonomous testing components
- **Tools**: Browser automation, code execution, file manipulation
- **Prompts**: Security testing scenarios and templates
- **Interface**: CLI and TUI for user interaction
- **Runtime**: Docker-based execution environment

---

*For more information, see the [README](./README.md)*
"""

        # Write file
        index_file = self.docs_path / 'index.md'
        with open(index_file, 'w', encoding='utf-8') as f:
            f.write(index_md)

        print("  Created index.md")

    def generate_comprehensive_book(self):
        """Generate comprehensive_book.md by stitching together documentation."""
        print("Generating comprehensive_book.md...")

        book_md = f"""# Strix: Comprehensive Documentation Book

**Repository**: rbarfinezhadfeli0/strix
**Generated**: {datetime.now().isoformat()}

---

## Table of Contents

1. [Introduction](#introduction)
2. [Repository Overview](#repository-overview)
3. [Architecture](#architecture)
4. [Detailed Documentation](#detailed-documentation)

---

## Introduction

This comprehensive book contains complete documentation for the Strix security testing framework.
All content was automatically generated from the source repository.

Strix is an AI-powered security testing framework that leverages language models to perform
intelligent security assessments of web applications and APIs.

---

## Repository Overview

"""

        # Add root doc.md content
        try:
            root_doc = self.docs_path / 'doc.md'
            if root_doc.exists():
                with open(root_doc, 'r', encoding='utf-8') as f:
                    book_md += f.read() + "\n\n---\n\n"
        except:
            pass

        # Process folders in logical order
        folder_order = [
            'strix',
            'strix/agents',
            'strix/agents/StrixAgent',
            'strix/tools',
            'strix/llm',
            'strix/prompts',
            'strix/interface',
            'strix/runtime',
            'strix/telemetry',
            'containers',
        ]

        for folder_rel in folder_order:
            folder_path = self.docs_path / folder_rel
            if not folder_path.exists():
                continue

            book_md += f"## {folder_rel}\n\n"

            # Add folder doc.md
            doc_file = folder_path / 'doc.md'
            if doc_file.exists():
                try:
                    with open(doc_file, 'r', encoding='utf-8') as f:
                        content = f.read()
                        # Remove the title (first line)
                        lines = content.split('\n')
                        book_md += '\n'.join(lines[1:]) + "\n\n"
                except:
                    pass

            book_md += "---\n\n"

        # Add summary statistics
        book_md += """
## Summary

This documentation book was automatically generated and includes:

- Complete source code for all repository files
- Detailed analysis of Python modules, classes, and functions
- Keyword extraction and indexing
- Architectural overviews
- Security testing templates and prompts

For the interactive version, navigate through the folder structure starting at [index.md](./index.md).

---

*Generated by World's Best Repo Book Generator*
"""

        # Write file
        book_file = self.docs_path / 'comprehensive_book.md'
        with open(book_file, 'w', encoding='utf-8') as f:
            f.write(book_md)

        word_count = len(book_md.split())
        print(f"  Created comprehensive_book.md ({word_count} words)")

def main():
    """Main entry point."""
    docs_path = "/home/user/strix/docs"
    repo_path = "/home/user/strix"

    generator = GlobalDocGenerator(docs_path, repo_path)

    generator.generate_keywords_md()
    generator.generate_index_md()
    generator.generate_comprehensive_book()

    print("\n=== GLOBAL DOCUMENTATION COMPLETE ===")

if __name__ == "__main__":
    main()
